## Introduction

### Why Python?

- Easy to learn, very popular, very powerfull
- Can be used both for research and developement
- A lot of libraries and modules are available

### Install Python

1. Go to [this address](https://www.anaconda.com/download/) and download and install **Anaconda**. (version 3.7)
2. Run command prompt (or PowerShell).
3. Type in `jupyter notebook` and press `<Enter>`.
4. Create a new `notebook` and start programming in Python.

## Python Basics

### Arithmatic Operations

### Logical Operations

#### AND, OR, NOT

<img src='imgs/logical_operators.png' width='75%'>

### Variables

<div class="alert alert-info">
    <strong>Variable:</strong>
    <ul>
        <li>A variable is a name for a specific location in the memory.</li>
        <li>A variable has a `name`, a `type` and a `value`.</li>
    </ul>
</div>

- In python, we only specify the `name` and the `value`.
- The `type` is determined automatically from the assigned value.

### modules

Always, you can use `dir()` and `help()` to see inside a module.

### Data structures in python

- **List:** A sequence of items.
- **Tuple:** like list, but it is *immutable*.
- **Set:** A collection of distinct items in which the order in not important.
- **Dictinary:** A list of (key, value) pairs.

 ```python
   # List
   my_courses = ["Machine Learning", "Pattern Recognition", "Image Processing"]
   my_grades = [16.5, 18.25, 16.5]
```

```python
   # Tuple
   my_courses = ("Machine Learning", "Pattern Recognition", "Image Processing")
   my_grades = (16.5, 18.25, 16.5)
```

```python
   # Set
   my_courses = {"Machine Learning", "Pattern Recognition", "Image Processing"}
   my_grades = {16.5, 18.25}
```

```python
   # Dictionary
   my_courses = {"Machine Learning": 16.5, 
                 "Pattern Recognition": 18.25, 
                 "Image Processing":15.0}
```

## Vectors and Matrices

In machine learning we almost always use matrices to:
- Represent **inputs**
- Represent **outpus**
- Represent **parameters**

<img src="imgs/cat-matrix.png" width="50%"/>

<div class="alert alert-info">
    <strong>Matrix</strong> A matrix is a rectangular array of numbers.
    <ul>
        <li>In python, we use `numpy` package to work with matrices.</li>
        <li>First, we need to import this package to be able to use it.</li>
    </ul>
</div>

* To import `numpy` package, we use the following statement:
```python
import numpy as np
```

In [3]:
import numpy as np

In [1]:
#!pip install numpy

If the above statement fails, you need to install `numpy` package, using: 
- `pip install numpy` in the Command Prompt, or
- `!pip install numpy` in the notebook.
 
**Note.** if you are using the Anaconda distribution, it has `numpy` package and many other useful packages pre-installed.

<img src='imgs/tensors.png' width='60%'>

### Random vectors and matrices

Identity matrix

## Data Operations

In [52]:
A = np.array([[1., 2], [3, 4], [5, 6]])

In [53]:
A

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

<h6>Reading data from a text file</h6>

<img src='imgs/house_price_dataset.png' width='50%'>

Save data as text

Save and load as numpy format (.npy)

## Colon Operator (:)

<img src='imgs/matrix.png' width='30%'>

Flattening a matrix

In [87]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [88]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

### Matrix concatination

In [94]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[11, 12], [13, 14], [15, 16]])

## Matrix Operations

In [103]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[11, 12], [13, 14], [15, 16]])
C = np.array([[1, 1], [2, 2]])

Preffered ways for matrix multiplication:
- `np.matmul(A, C)`
- `A @ C`

Element-wise matrix multiplication (Hadamard multiplication)

**Note:** The dimensions should be the same.

In [113]:
v = np.array([[1], [2], [3]])

Suppose we want to add 1 to every element of vector `v`.

#### Transpose

In [124]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [125]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

#### Other matrix operations

In [127]:
a = np.array([1, 15, 2, 0.5])

Magic Square (3 x 3)

In [133]:
A = np.array(([[8, 1, 6], 
               [3, 5, 7], 
               [4, 9, 2]]))

In [144]:
A

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

#### Inverse

In [22]:
A = np.array(([[8, 1, 6], 
               [3, 5, 7], 
               [4, 9, 2]]))

In [23]:
np.linalg.inv(A)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [24]:
np.linalg.pinv(A)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [25]:
from numpy.linalg import inv, pinv

In [26]:
inv(A.T @ A) @ A.T  # A+ (pseudo-inverse)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

If $A$ is non-singular:

$$A^{+} = (A^T A)^{-1} A^T = A^{-1} (A^T)^{-1} A^T = A^{-1} [(A^T)^{-1} A^T] = A^{-1} I = A^{-1}$$

In [27]:
inv(A)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [15]:
A=np.array([[1,2],[3,6],[5,10]])
A

array([[ 1,  2],
       [ 3,  6],
       [ 5, 10]])

In [20]:
## Псевдообратная матрица


In [19]:
pinv(A)

array([[0.00571429, 0.01714286, 0.02857143],
       [0.01142857, 0.03428571, 0.05714286]])

## Plotting

In [31]:
import math
import matplotlib.pyplot as plt
%matplotlib inline

In [34]:
t = np.arange(0., 1., .01)

In [35]:
print(t[:10])

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]


In [36]:
y1 = np.sin(2 * math.pi * t)

Saving plots

#### Subplots

<img src='imgs/subplot.jpg' width='50%'>

## Control Structures

- Conditional Statements
- Loops
- functions

### If Statements

In [188]:
np.random.rand()

0.10054645646364735

### Functions