## Introduction

### Why Python?

- Easy to learn, very popular, very powerfull
- Can be used both for research and developement
- A lot of libraries and modules are available

### Install Python

1. Go to [this address](https://www.anaconda.com/download/) and download and install **Anaconda**. (version 3.7)
2. Run command prompt (or PowerShell).
3. Type in `jupyter notebook` and press `<Enter>`.
4. Create a new `notebook` and start programming in Python.

## Python Basics

### Arithmatic Operations

In [2]:
print(3-2)
print(5+6)
print(1 / 2)
print(1 // 2)
print(2** 6)



1
11
0.5
0
64


### Logical Operations

#### AND, OR, NOT

In [4]:
print( 1 ==2 )
print( 1 != 2)

False
True


<img src='imgs/logical_operators.png' width='75%'>

In [5]:
print( not False)

True


In [9]:
print( False and False )

print( 10 >5 and 11 >20)

print( 10 >5 or 11 >20)

False
False
True


### Variables

<div class="alert alert-info">
    <strong>Variable:</strong>
    <ul>
        <li>A variable is a name for a specific location in the memory.</li>
        <li>A variable has a `name`, a `type` and a `value`.</li>
    </ul>
</div>

- In python, we only specify the `name` and the `value`.
- The `type` is determined automatically from the assigned value.

### modules

Always, you can use `dir()` and `help()` to see inside a module.

In [10]:
a=3
type(a)

int

In [12]:
a=3.0
type(int(a))

int

In [17]:
b = 'Hi, I love Python!'


hi, i love python!


In [24]:
A="hello"

A+A

'hellohello'

In [26]:
A=input()
B=input()

print(int(A)+int(B))

10
20
30


In [16]:
b[0]="U"

TypeError: 'str' object does not support item assignment

In [15]:
A=[1,2,3,4]
A[0]=20
print(A)

[20, 2, 3, 4]


In [18]:
A=True

type(A)

bool

In [19]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [21]:
help(str.lower)

Help on method_descriptor:

lower(self, /)
    Return a copy of the string converted to lowercase.



### Data structures in python

- **List:** A sequence of items.
- **Tuple:** like list, but it is *immutable*.
- **Set:** A collection of distinct items in which the order in not important.
- **Dictinary:** A list of (key, value) pairs.

 ```python
   # List
   my_courses = ["Machine Learning", "Pattern Recognition", "Image Processing"]
   my_grades = [16.5, 18.25, 16.5]
```

```python
   # Tuple
   my_courses = ("Machine Learning", "Pattern Recognition", "Image Processing")
   my_grades = (16.5, 18.25, 16.5)
```

```python
   # Set
   my_courses = {"Machine Learning", "Pattern Recognition", "Image Processing"}
   my_grades = {16.5, 18.25}
```

```python
   # Dictionary
   my_courses = {"Machine Learning": 16.5, 
                 "Pattern Recognition": 18.25, 
                 "Image Processing":15.0}
```

In [42]:
A=[10,20,30]

A=[10,"fdsf",10.2]
print(A)

A.append(30)


A.extend([20,30,40,"fsdfds"])

print(A)

[10, 'fdsf', 10.2]
[10, 'fdsf', 10.2, 30, 20, 30, 40, 'fsdfds']


In [39]:
A.pop()

print(A)

[10, 'fdsf', 30, 20, 30, 40, 'fsdfds']


In [44]:
A.clear()
print(A)

[]


In [45]:
id(A)

1897967689216

In [46]:
del A

In [47]:
id(A)

NameError: name 'A' is not defined

In [37]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [54]:
A=[1,2,3,4]
B=A.copy()
print(A)

print(B)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [50]:
A[0]=100

In [51]:
print(A)

print(B)

[100, 2, 3, 4]
[100, 2, 3, 4]


In [55]:
print(id(A))
print(id(B))

1897971277248
1897967026688


In [57]:
A=(10,20,30)

type(A)

tuple

In [58]:
A[0]

10

In [72]:
A=[1,2,3,4]
A[::-1]

[4, 3, 2, 1]

In [66]:
t="Machine Learning"
t[8:10]

'Le'

In [74]:

for i in range(len(A)):
    print(A[i])

1
2
3
4


In [70]:
A=range(10)

print(list(A))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [79]:
A={1,2,3,4,5,5,5,5,5,3,2,1}




TypeError: 'set' object is not subscriptable

In [94]:
A={1,2,3,4,5}
B={2,5,10}

#A.intersection(B)


In [95]:
A.union(B)

{1, 2, 3, 4, 5, 10}

In [96]:
A | B

{1, 2, 3, 4, 5, 10}

In [100]:
A={1,2,3,4,5}
print(A)
A.add(50)
A.add(50)
A.add(50)
print(A)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 50}


In [98]:
dir(set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [103]:
A={"name":"Ivan","tel":"999"}


In [110]:
A={"name":"Ivan","tel":999}

In [113]:
print(len(A))
print(A)

2
{'name': 'Ivan', 'tel': 999}


In [107]:
A={[1,2,3]:"fdsfs"}

TypeError: unhashable type: 'list'

In [108]:
A={(1,2,3):"fdsfs"}

In [109]:
A

{(1, 2, 3): 'fdsfs'}

In [38]:
help(list.pop)

Help on method_descriptor:

pop(self, index=-1, /)
    Remove and return item at index (default last).
    
    Raises IndexError if list is empty or index is out of range.



## Vectors and Matrices

In machine learning we almost always use matrices to:
- Represent **inputs**
- Represent **outpus**
- Represent **parameters**

<img src="imgs/cat-matrix.png" width="50%"/>

<div class="alert alert-info">
    <strong>Matrix</strong> A matrix is a rectangular array of numbers.
    <ul>
        <li>In python, we use `numpy` package to work with matrices.</li>
        <li>First, we need to import this package to be able to use it.</li>
    </ul>
</div>

* To import `numpy` package, we use the following statement:
```python
import numpy as np
```

In [3]:
import numpy as np

In [1]:
#!pip install numpy

If the above statement fails, you need to install `numpy` package, using: 
- `pip install numpy` in the Command Prompt, or
- `!pip install numpy` in the notebook.
 
**Note.** if you are using the Anaconda distribution, it has `numpy` package and many other useful packages pre-installed.

<img src='imgs/tensors.png' width='60%'>

### Random vectors and matrices

Identity matrix

## Data Operations

In [52]:
A = np.array([[1., 2], [3, 4], [5, 6]])

In [53]:
A

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

<h6>Reading data from a text file</h6>

<img src='imgs/house_price_dataset.png' width='50%'>

Save data as text

Save and load as numpy format (.npy)

## Colon Operator (:)

<img src='imgs/matrix.png' width='30%'>

Flattening a matrix

In [87]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [88]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

### Matrix concatination

In [94]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[11, 12], [13, 14], [15, 16]])

## Matrix Operations

In [103]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[11, 12], [13, 14], [15, 16]])
C = np.array([[1, 1], [2, 2]])

Preffered ways for matrix multiplication:
- `np.matmul(A, C)`
- `A @ C`

Element-wise matrix multiplication (Hadamard multiplication)

**Note:** The dimensions should be the same.

In [113]:
v = np.array([[1], [2], [3]])

Suppose we want to add 1 to every element of vector `v`.

#### Transpose

In [124]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [125]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

#### Other matrix operations

In [127]:
a = np.array([1, 15, 2, 0.5])

Magic Square (3 x 3)

In [133]:
A = np.array(([[8, 1, 6], 
               [3, 5, 7], 
               [4, 9, 2]]))

In [144]:
A

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

#### Inverse

In [22]:
A = np.array(([[8, 1, 6], 
               [3, 5, 7], 
               [4, 9, 2]]))

In [23]:
np.linalg.inv(A)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [24]:
np.linalg.pinv(A)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [25]:
from numpy.linalg import inv, pinv

In [26]:
inv(A.T @ A) @ A.T  # A+ (pseudo-inverse)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

If $A$ is non-singular:

$$A^{+} = (A^T A)^{-1} A^T = A^{-1} (A^T)^{-1} A^T = A^{-1} [(A^T)^{-1} A^T] = A^{-1} I = A^{-1}$$

In [27]:
inv(A)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [15]:
A=np.array([[1,2],[3,6],[5,10]])
A

array([[ 1,  2],
       [ 3,  6],
       [ 5, 10]])

In [20]:
## Псевдообратная матрица


In [19]:
pinv(A)

array([[0.00571429, 0.01714286, 0.02857143],
       [0.01142857, 0.03428571, 0.05714286]])

## Plotting

In [31]:
import math
import matplotlib.pyplot as plt
%matplotlib inline

In [34]:
t = np.arange(0., 1., .01)

In [35]:
print(t[:10])

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]


In [36]:
y1 = np.sin(2 * math.pi * t)

Saving plots

#### Subplots

<img src='imgs/subplot.jpg' width='50%'>

## Control Structures

- Conditional Statements
- Loops
- functions

### If Statements

In [188]:
np.random.rand()

0.10054645646364735

### Functions